# Generated by Django 5.2.6 on 2025-09-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0002_destination_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cruises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=2000)),
                ('passengers', models.IntegerField()),
            ],
        ),
    ]
