# Generated by Django 5.2.6 on 2025-09-18 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0003_cruises'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cruises',
            new_name='Cruise',
        ),
    ]
