# Generated by Django 5.2.6 on 2025-09-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0004_rename_cruises_cruise'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruise',
            name='destinations',
            field=models.ManyToManyField(related_name='cruises', to='relecloud.destination'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='passengers',
            field=models.PositiveIntegerField(),
        ),
    ]
