# Generated by Django 5.2.6 on 2025-09-25 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0005_cruise_destinations_alter_cruise_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='country',
        ),
    ]
