# Generated by Django 5.2.6 on 2025-09-26 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0006_remove_destination_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='travel_time',
            field=models.DurationField(default=datetime.timedelta(days=1), help_text='Approximate travel time'),
        ),
    ]
